### ISSUE TITLE
Identify global metric value for each feature

### ISSUE THREAD

**Issue by brynamo** [brynamo/face2emoji#1]
Hey guys, in order to edit the UIControlers (the little graphs that visualize the value) we need to find where these values are stored. Looks like they are part of the objects but personally I'm a little confused on how to access them. 

If you either of you guys have ideas where to find the metrics just let the others know!

**Comment by jchou** [comment]
- In `AffdexDemoViewController`, `self.availableClassifiers` is just a collection of:
  - `self.emotions` (e.g., anger, contempt, disgust) and
  - `self.expressions` (e.g., brow raise, chin raise, lip pucker).
- An `ExpressionViewController` is a `UIViewController` + some data like the `metric`, `name` of its classifier, etc. See `ExpressionViewController.h`.
- `AffdexDemoViewController.m` acquires the `score` of each classifier in `availableClassifiers`, but its name is deceiving because the `score` of a classifier is actually a string like `angerScore` or `browRaiseScore` -- see `initWithCoder` in `AffdexDemoViewController.m`
- All the data is lumped into this big `face` object, and the actual values can be extracted from `face` using the `score` key we want
  - e.g., If we wanted the anger metric, we would get `angerScore` value from `face`

I'm a little uncertain how/where `setMetric` is called in `ExpressionViewController.h`...
